fix: set $parent when creating zeebe:CalledElement element
camunda/camunda-bpmn-js pull request #99
Opened 2022-03-23 15:06 UTC by philippfromme

2022-03-24 10:08 UTC, nikku requested changes
MacOS does not seem to [approve this PR](https://github.com/camunda/camunda-bpmn-js/runs/5662525656?check_suite_focus=true).

2022-03-24 10:51 UTC, pinussilvestrus commented
Probably related (and what is really annoying): https://github.com/camunda/camunda-bpmn-js/issues/85

2022-03-24 12:18 UTC, philippfromme commented
Sorry, wasn't even meant to be reviewed because of failing tests.

2022-03-28 15:58 UTC, barmac approved these changes
I'd rather want this to be handled by `moddle` but the PR looks good 👍

2022-03-28 19:01 UTC, merged